debug: False # 是否开启调试模式

#需要自行获取
sessdata: "" # 你的SESSDATA
bili_jct: "" # 你的bili_jct
buvid3: "" # 你的buvid3
dedeuserid: "" # 你的dedeuserid
ac_time_value: "" # 你的ac_time_value
room: "" # 直播间id
uid: "" # 主播的uid

# 检测配置
刷屏检测时间窗口: 60  # 检测时间窗口（秒）
刷屏处理方式: "禁言"  # 禁言或拉黑
禁言时长: 2  # 自动解禁时间（小时）

#非关键词检测配置
开启普通刷屏检测: false  # 是否开启刷屏检测非关键词列表: 
刷屏检测最大消息数: 8  # 非关键词检测时间窗口内允许的最大消息数

# 关键词刷屏检测
开启关键词刷屏检测: true  # 是否开启关键词刷屏检测
关键词最大消息数: 3  # 关键词时间窗口内允许的关键词消息数
关键词列表:
  - "喝"
  - "思考"
  - "惊讶"
  - "疑惑"
  - "\\[[\\s\\S]+\\]"
  
# 定时公告配置
公告发送间隔: 600  # 发送间隔（秒），600秒=10分钟
公告内容: "直播间刷屏自动禁言，2小时自动解除"  # 公告内容
